movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'


urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    des=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name','des','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from . forms import MovieForm

# Create your views here.

def index(request):
    item=movie.objects.all()
    context={
        'movie_list':item
    }
    return render(request,'index.html',context)
def details(request,movie_id):
    token=movie.objects.get(id=movie_id)
    return render(request,"details.html",{'token':token})


def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        des = request.POST.get('des')
        year = request.POST.get('year')
        img = request.FILES['img']
        item=movie(name=name,des=des,year=year,img=img)
        item.save()
    return render(request,"add.html")

def update(request,id):
    item1=movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=item1)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form1':form,'item1':item1})

def delete(request,id):
    if request.method=='POST':
        item=movie.objects.get(id=id)
        item.delete()
        return redirect('/')
    return render(request,"delete.html")

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <input type="text" name="des" placeholder="enter movie description">
    <input type="text" name="year" placeholder="enter published year">
    <input type="file" name="img">
    <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

  Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  are you want to delete this movie?
  <input type="submit">
</form>
{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{token.img.url}}" width="300" height="300">
        </div>
<div class="col-md-6">
    <h1>{{token.name}}</h1><br>
    {{token.des}}
    {{token.year}}<br>
    <a class="btn btn-warning" href="{% url 'movieapp:update' token.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' token.id %}">delete</a>
</div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form1.as_p}}
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
  <img src="{{i.img.url}}" class="Card image cap" alt="" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.des}} </p>
    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Movie Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>





{% endblock %}